# -*- coding: utf-8 -*-
"""Image_prep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bJRmhuphQsTgN5S7_q-CJErGxPtsRvdt
"""

import pandas as pd
from google.colab import drive
import os
import shutil

# mount to Google Drive account 
drive.mount('/content/drive', force_remount=True)
os.chdir("/content/drive/My Drive/GSOC2020/Training Model")

# read in metadata and keep the file name, caption, politician name, and office 
img_files = pd.read_csv("annotation_sample_random_metadata.csv")
img_files = img_files[['filename','caption', 'name', 'Election']]
num_rows = img_files.shape[0]

# make directory in which to store annotation folders
os.mkdir("annotation_folders")

for i in range(num_rows):
  # create a new folder for image annotation
  os.chdir("/content/drive/My Drive/GSOC2020/Training Model/annotation_folders")
  folder_num = i + 1
  os.mkdir(f"{folder_num}")
  os.chdir(f"/content/drive/My Drive/GSOC2020/Training Model/annotation_folders/{folder_num}")
  
  # move Facebook image into this folder
  img_Facebook = img_files.iloc[i]['filename']
  shutil.move(f"/content/drive/My Drive/GSOC2020/Training Model/annotation_sample_random/{img_Facebook}", f"/content/drive/My Drive/GSOC2020/Training Model/annotation_folders/{folder_num}")
  
  # write Facebook caption as a txt file in this folder
  caption_txt = open(f"{img_Facebook}.txt", mode="w")
  caption = img_files.iloc[i]['caption']
  caption_txt.write(f"{caption}")
  caption_txt.close
  
  # move a copy of the corresponding polician image into this folder
  if img_files.iloc[i]['Election'] == "House":
    chamber = "houses"
  elif img_files.iloc[i]['Election'] == "Governor":
    chamber = "govornor"
  elif img_files.iloc[i]['Election'] == "Senate":
    chamber = "senates"
  politician_name = img_files.iloc[i]['name'].rstrip()
  try:
    politician_img = f"facebook_dataset_{chamber}_{politician_name}.jpg"
    shutil.copy(f"/content/drive/My Drive/GSOC2020/Training Model/politician/{politician_img}",f"/content/drive/My Drive/GSOC2020/Training Model/politician/{politician_img}*annotate")
    shutil.move(f"/content/drive/My Drive/GSOC2020/Training Model/politician/{politician_img}*annotate", f"/content/drive/My Drive/GSOC2020/Training Model/annotation_folders/{folder_num}")
  except FileNotFoundError:
    politician_img = f"facebook_dataset_{chamber}_{politician_name}.jpeg"
    shutil.copy(f"/content/drive/My Drive/GSOC2020/Training Model/politician/{politician_img}",f"/content/drive/My Drive/GSOC2020/Training Model/politician/{politician_img}*annotate")
    shutil.move(f"/content/drive/My Drive/GSOC2020/Training Model/politician/{politician_img}*annotate", f"/content/drive/My Drive/GSOC2020/Training Model/annotation_folders/{folder_num}")